### ISSUE TITLE
Bad regression in 0.4.1

### ISSUE THREAD

**Issue by ffurano** [cern-it-sdc-id/davix#1]
Davix 0.4.1 in epel seems affected by two regression bugs:

- it prints CRs on the screen at every attempt
- davix-get is rejected by S3 when redirected to it (HEAD gets 401)

This is affecting the Data Bridge operation.

Davix 0.4.1-dev works perfectly instead. I suspect a bad error in the last push to epel, or an unfortunate push to the git head.

**Comment by ffurano** [comment]
git checkout e2b6a0762c65d55196587e430c86662841c4e83d

this works. Probably just an inserted bug in one of the subsequent commits.

**Comment by gbitzes** [comment]
Hi Fabrizio, is this issue still relevant? Should I close it?
