### ISSUE TITLE
Cache login credentials

### ISSUE THREAD

**Issue by wpoely86** [cern-it-sdc-id/davix#12]
When I do something like:
```
davix-put -r 4 a-directory https://somehost.com/owncloud/remote.php/webdav/remotedir/
```
it works but it ask for login credentials for every file it wants to upload. Could this please be cached?

**Comment by gbitzes** [comment]
Hi, thanks for the bug report, I'll push a fix tomorrow. In the meantime, you could specify username and password in the command line with --userlogin and --userpass, this should work.

**Comment by wpoely86** [comment]
I know but specifying a password on the command line is *very* unsafe.

**Comment by gbitzes** [comment]
Fix pushed, let me know if you find more bugs. Thanks
