### ISSUE TITLE
Behaviour in forked processes

### ISSUE THREAD

**Issue by gganis** [cern-it-sdc-id/davix#15]
It looks like davix cannot be used in child processes if already used in the parent forking the child. 
Spurious buffers maybe present in new connections open by children. In a test ROOT application the problem is systematically occurring when more than 3 child processes are created, rare with 1 or 2 children.

It looks like something does not get re-initialized on subsequent open calls.

Any hint would be welcome.
Is there a way to completely reset Davix in a new process?
 
A ROOT reproducer can be provided if needed.

**Comment by gbitzes** [comment]
Indeed, I don't think davix has been designed with explicit support for forked processes, I'm not sure how easy it'll be to add it. In theory, if there isn't an active davix context at the point of forking,  both parent and child should be able to use the library by creating a new context.

Yes, example code on how to reproduce the problem would be much appreciated.

**Comment by gganis** [comment]
Thanks for the prompt reply.
Can you work with the ROOT master?

**Comment by gbitzes** [comment]
Yes, just let me know the commit of ROOT you're working with and I'll compile it.

**Comment by gganis** [comment]
Any commit since Friday afternoon (specifically any commit including c4712f03106c50c8fc1e789e7d21cae1434a22f3).
Under tutorials/multicore there is a new tutorial mp103_processSelector.C. To reproduce the problem uncomment the lines defining  __reproduce_davix .
You can run the tutorial with
 $ root -l -q tutorials/multicore/mp103_processSelector.C
If built with -Dtesting=ON, you can use
 $ ctest -V -R mp103_processSelector

Let me know if you need any help.

**Comment by gbitzes** [comment]
Hi, I'm running the example. Is this the message that indicates the error? I don't get any crashes.
`Error in <TDavixFile::Init>: http://root.cern.ch/files/h1/dstarmb.root not a ROOT file`

If I disable connection reuse in davix, the message goes away. It seems that the forked process is trying to re-use the old TCP connection of the parent. I'll see about installing some kind of fork handler, which clears the session cache.

**Comment by gganis** [comment]
Hi,
Yes, that is the indication of the problem.
It does not crash any longer because I have added a protection and error handling.
The forked process get something unexpected when it establish a connection for a new file. I assume this is
because it re-uses improperly something from the parent.

Thanks for looking at it.

**Comment by gbitzes** [comment]
The solution I implemented is to keep track of all allocated davix contexts, and after a fork go through all of them in the child process and clear their session caches.

Seems to work, the error message is gone. I'm not sure how fork-safe davix is now, certainly not if a transfer is currently taking place, but this specific case seems fine. Feel free to give it a try, you can get the latest development version from our [unstable](https://dmc.web.cern.ch/repositories) repos.

Thanks for the report! The fix will land in davix 0.6.5.
