### ISSUE TITLE
FTBFS with openssl 1.1.0

### ISSUE THREAD

**Issue by ellert** [cern-it-sdc-id/davix#16]
davix does not compile with openssl 1.1.0, as reported to Debian BTS:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828279

**Comment by gbitzes** [comment]
Many thanks for the report, I'm having a look.

**Comment by gbitzes** [comment]
The fix has been committed and will land in davix 0.6.5, thanks for the report.
