### ISSUE TITLE
davix-put fails on files with spaces in their names

### ISSUE THREAD

**Issue by pol** [cern-it-sdc-id/davix#17]
Version: built from latest github source

davix-put with the following options:

-r10 -k --no-100-continue

Getting errors that look like this:

Davix::DavixOp::PutOp Failed to PUT /<path truncated for privacy>/2D_seismic_data/kevin_2D/SEG Y Export Job.LOG
(Davix::HttpRequest) Error:  davs://dav.box.com/dav/<path truncated for privacy>/2D_seismic_data/kevin_2D/SEG Y Export Job.LOG is not not a valid HTTP or Webdav URL

This seems to be happening with every file that has a space in the name.  I think the URL is not being quoted (or special characters are not being URL encoded).

**Comment by gbitzes** [comment]
Hi,

Yes, davix is expecting a URL which has already been URL-encoded. If you replace the spaces with %20, it should work. (curl also doesn't handle raw spaces in the URL, as far I see)

**Comment by pol** [comment]
What do you recommend for a recursive upload?  I am not specifying the filenames in that case, davix is.

**Comment by gbitzes** [comment]
Ah, now I see, that's definitely a bug then. I'll take a look.

**Comment by gbitzes** [comment]
I found the bug, and I can reproduce the problem, but now I see that many places have to be fixed in the code, as other operations also have this problem, such as recursive GET on a directory. I'll post a fix soon.

Thanks for the bug report, by the way

**Comment by pol** [comment]
No problem, thanks for developing the tool.

**Comment by gbitzes** [comment]
Hi,

It should behave better with weird characters now, feel free to test and if it doesn't work, reopen the issue. (I'm not sure I've caught all instances of unsafe concatenation.. )

Thanks for the bug report!
