### ISSUE TITLE
Finduuid.cmake is not suitable for MacOS

### ISSUE THREAD

**Issue by amadio** [cern-it-sdc-id/davix#25]
On MacOS the kernel provides uuid functions (e.g. `uuid_generate_random()`)  without the need to link to libuuid.so: https://developer.apple.com/documentation/kernel/1470612-uuid_generate_random?language=objc.

However the `Finduuid.cmake` module checks for the library and fails to configure if it's not found.
Even on Linux the functions come from the kernel (on my system libuuid.so exists, but has no symbols).

Please consider updating the module to not require the library (or I could create a pull request, just let me know).

**Comment by gbitzes** [comment]
I see, thanks for reporting this issue. I'm not intimately familiar with MacOS, please feel free to send a pull request.

Do you know from which version and on the Linux kernel provides the uuid symbols? If it works on SLC6, we could drop libuuid dependency entirely.

**Comment by amadio** [comment]
Sure, I will make a PR. For Linux I looked a bit more and the header `/usr/include/linux/uuid.h` does not have `uuid_generate_random()` in it. For Linux we need libuuid-devel (rpm), uuid-dev (deb), or sys-apps/util-linux (Gentoo Linux only) to get the `uuid/uuid.h` header and library. But on Macs the header seems to be sufficient.

Is it possible to compile Davix without OpenSSL support? I wonder because you have `find_package(OpenSSL)` and not `find_package(OpenSSL REQUIRED)` in `CMakeLists.txt.

**Comment by gbitzes** [comment]
About openssl: That's likely a mistake, I don't think davix will build without openssl.

About cmake: Minimum supported platform is SLC6, which has cmake3 using an epel package, so it could work.

Is there some feature you need from cmake3?

**Comment by amadio** [comment]
I would like to use `include(CheckCXXSymbolExists)` and I don't see any reference to it in CMake 2.x docs. If SLC6 is the only old platform, I can try on a container and make sure my changes work there.

**Comment by gbitzes** [comment]
Ok, no worries, feel free to use cmake3, I'll make sure build scripts etc work after your PR.

**Comment by amadio** [comment]
Sure, but it would be better if after my PR you don't need any extra changes :-).

**Comment by amadio** [comment]
Hi @gbitzes. I just created #27 to try to address this. Could you please try it and let me know if you have any problems? For ROOT's builtin Davix I use the same file, so it takes precedence over the one in Davix itself, and everything is working, but ROOT requires CMake 3.4.3.

**Comment by amadio** [comment]
Closed by PR #27, which has been merged.
