### ISSUE TITLE
Davix static library crash on CentOS7 

### ISSUE THREAD

**Issue by peremato** [cern-it-sdc-id/davix#6]
Environment:
- Davix version 0.3.6 with embedded externals and statically build. 
- ROOT master build with -Dbuiltin_davix=ON
- CentOS7 with native compiler (gcc 4.8)

The traceback
~~~
#10 0x00007fd5daf680d3 in std::string::size() const () from /lib64/libstdc++.so.6
#11 0x00007fd5db51f3b7 in std::operator+<char, std::char_traits<char>, std::allocator<char> > (__lhs=0x7fd5cd0cdc3f " davix/", __rhs=<error reading variable: Cannot access memory at address 0xffffffffffffffe8>) at /usr/include/c++/4.8.2/bits/basic_string.tcc:700
#12 0x00007fd5ccf09ba8 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /mnt/build/jenkins/workspace/root-package/BUILDTYPE/Release/COMPILER/native/LABEL/cc7/VERSION/master/root/net/davix/src/TDavixFile.cxx:60
#13 0x00007fd5ccf09c78 in _GLOBAL__sub_I_TDavixFile.cxx(void) () at /mnt/build/jenkins/workspace/root-package/BUILDTYPE/Release/COMPILER/native/LABEL/cc7/VERSION/master/root/net/davix/src/TDavixFile.cxx:721
#14 0x00007fd5dbb6f4e3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#15 0x00007fd5dbb73b04 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#16 0x00007fd5dbb6f2f4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#17 0x00007fd5dbb7321b in _dl_open () from /lib64/ld-linux-x86-64.so.2
#18 0x00007fd5d9f9d02b in dlopen_doit () from /lib64/libdl.so.2
#19 0x00007fd5dbb6f2f4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#20 0x00007fd5d9f9d62d in _dlerror_run () from /lib64/libdl.so.2
#21 0x00007fd5d9f9d0c1 in dlopen
~~~

The problem is that TDavixFile.cxx uses Davix::version() in an static initialization and is probably not initialized yet.

**Comment by gbitzes** [comment]
Hi Pere,

I confirm I can reproduce the issue, I built ROOT on a CentOS7 VM and get the same crash. Both `gUserAgent` of TDavixFile and `_version` of davix are static strings, and vulnerable to the "static initialization order fiasco"..

In this case, `gUserAgent` is apparently initialized first, and at the time `version()` is called, `_version` has not been initialized yet.. The function returns a reference to a memory location containing uninitialized data.

Thanks for the ticket and the fix - I've integrated it to davix.
