### ISSUE TITLE
davix leaks file descriptors

### ISSUE THREAD

**Issue by apeters1971** [cern-it-sdc-id/davix#8]
The davix library leaks one file descriptor for write-opened file.
```
lrwx------. 1 root   root   64 Feb 11 13:25 66 -> /tmp/.davix_tmp_file_XXXXXXXXXXXXXXXXXXyzgG0q (deleted)
lrwx------. 1 root   root   64 Feb 11 13:25 65 -> /tmp/.davix_tmp_file_XXXXXXXXXXXXXXXXXXZ6E10r (deleted)
lrwx------. 1 root   root   64 Feb 11 13:25 63 -> /tmp/.davix_tmp_file_XXXXXXXXXXXXXXXXXXItaC8s (deleted)
```

The error is in the desctructor here, it unlinks the temporary file, but does not close _fd.

```
struct IOBufferLocalFile{
    IOBufferLocalFile(int fd, const std::string & filepath): _fd(fd), _filepath(filepath){}
    virtual ~IOBufferLocalFile(){
        DAVIX_SLOG(DAVIX_LOG_TRACE, DAVIX_LOG_CHAIN, "Delete tmp file {}", _filepath);
        unlink(_filepath.c_str());
    }
    int _fd;
    std::string _filepath;
};

```

It would be also very nice, if the stage location could be modified because /tmp/ is not an optimal place for staging possibly large files.

**Comment by gbitzes** [comment]
Hi, thanks for the bug report. I committed a fix, now the file descriptor is closed after unlinking.

About the stage location, maybe it could be user-configurable by using an environment variable. Another idea might be to use a named pipe, but if the file is too large it might not fit in memory+swap.

**Comment by apeters1971** [comment]
A local file is like memory anyway, so environment variable is asolutly sufficient and the most comfortable solution. Thanks Andreas.

**Comment by gbitzes** [comment]
I've added the ability to select location for the staging area through DAVIX_STAGING_AREA.
I'm closing this issue then - cheers.

**Comment by apeters1971** [comment]
Cool thanks, 
do you know when an updated version can be available via EPEL or is there a local repo which I can use for tests?

**Comment by gbitzes** [comment]
We will be releasing a new version of davix soon, but the procedure usually takes time. You can find the most recent version in our unstable repositories, which is updated automatically with every commit to devel: http://dmc.web.cern.ch/repositories

Let me know of any other issues you find - thanks.
